export const COURSE_SET = "COURSE_SET";
export const ERROR_SET = "ERROR_SET";
export const FIRST_NAME_SET = "FIRST_NAME_SET";
export const LAST_NAME_SET = "LAST_NAME_SET";
export const RESOLVING_SET = "RESOLVING_SET";
export const SUBSCRIPTION_SET = "SUBSCRIPTION_SET";
export const SUBSCRIPTIONS_SET = "SUBSCRIPTIONS_SET";